# Generated by Django 3.0.5 on 2020-04-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_user', models.CharField(max_length=16)),
                ('r_rank', models.CharField(max_length=16)),
                ('r_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_title', models.CharField(max_length=120)),
                ('t_content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=16, unique=True)),
                ('u_pwd', models.CharField(max_length=256)),
                ('u_img', models.ImageField(upload_to='icons')),
                ('u_response', models.IntegerField(default=0)),
                ('u_fans', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=16, null=True)),
                ('p_sex', models.BooleanField(blank=True, default=1, null=True)),
                ('p_tel', models.IntegerField(blank=True, null=True)),
                ('p_intro', models.TextField(blank=True, null=True)),
                ('person', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whokillsit.UserInfo')),
            ],
        ),
    ]
