# Generated by Django 3.0.5 on 2020-04-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whokillsit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personinfo',
            name='p_birth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='p_sex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='p_tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='u_img',
            field=models.ImageField(upload_to='icons/%Y/%m/%d/'),
        ),
    ]
