# Generated by Django 3.0.5 on 2020-04-19 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whokillsit', '0002_auto_20200419_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personinfo',
            old_name='p_birth',
            new_name='p_age',
        ),
    ]
