# Generated by Django 3.0.5 on 2020-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whokillsit', '0003_auto_20200419_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='u_email',
            field=models.CharField(default='example@outlook.com', max_length=128),
        ),
    ]
