# Generated by Django 3.0.5 on 2020-04-21 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whokillsit', '0004_userinfo_u_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_title', models.CharField(max_length=128)),
                ('s_content', models.TextField()),
                ('s_words', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whokillsit.UserInfo')),
            ],
        ),
    ]
