# Generated by Django 3.0.5 on 2020-04-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whokillsit', '0007_remark_r_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remark',
            old_name='r_user',
            new_name='r_name',
        ),
    ]
